import { useMemo } from "react";
import { motion } from "framer-motion";
import { SectionCard } from "./SectionCard";
import { parseSection, getSectionVariant } from "@/lib/contentParser";
import type { AnalysisObject } from "@/types/analysis";

interface DigestViewProps {
    data: AnalysisObject;
    recordId: string;
}

/**
 * Digest View - Text-focused Main Container
 *
 * Renders the complete digest with:
 * - Title and subtitle header
 * - LLM-generated section cards
 * - Footer
 */
export function DigestView({
    data,
    recordId
}: DigestViewProps) {
    // Parse the date for display
    const dateInfo = useMemo(() => {
        const date = typeof data.date === 'string' ? new Date(data.date) : data.date;
        return {
            formatted: date.toLocaleDateString('en-US', {
                weekday: 'long',
                month: 'long',
                day: 'numeric'
            }),
            time: data.scheduledTime || date.toLocaleTimeString('en-US', {
                hour: 'numeric',
                minute: '2-digit',
                hour12: true
            })
        };
    }, [data.date, data.scheduledTime]);

    // Parse sections into structured data
    const parsedSections = useMemo(() => {
        return data.sections.map(section => {
            const parsed = parseSection(section.heading, section.content);
            const variant = getSectionVariant(parsed);
            return { parsed, variant };
        });
    }, [data.sections]);

    return (
        <div className="digest-view pb-8">
            {/* Header with Title */}
            <motion.header
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, ease: "easeOut" }}
                className="text-center mb-8 px-4"
            >
                <h1 className="font-serif text-3xl md:text-4xl font-bold text-foreground leading-tight mb-4">
                    {data.title}
                </h1>
                <p className="font-sans text-muted-foreground text-sm">
                    {dateInfo.formatted} • {dateInfo.time}
                    {data.location && ` • ${data.location}`}
                </p>
            </motion.header>

            {/* Subtitle if present */}
            {data.subtitle && (
                <motion.p
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ duration: 0.5, delay: 0.3 }}
                    className="font-serif text-muted-foreground text-center text-lg leading-relaxed mb-8 px-4"
                >
                    {data.subtitle}
                </motion.p>
            )}

            {/* Section Cards */}
            <div className="px-4">
                {parsedSections.map(({ parsed, variant }, idx) => (
                    <SectionCard
                        key={idx}
                        section={parsed}
                        variant={variant}
                        recordId={recordId}
                        sectionIndex={idx}
                    />
                ))}
            </div>

            {/* Footer */}
            <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.5, delay: 0.5 }}
                className="text-center py-8 px-4"
            >
                <p className="font-sans text-muted-foreground text-sm">
                    🤖 You're all caught up
                </p>
                <p className="font-sans text-muted-foreground/50 text-xs mt-2">
                    Generated by Kowalski
                </p>
            </motion.div>
        </div>
    );
}
